apache/hawq

src/backend/cdb/cdbappendonlystorageread.c

For large tuples in a randomly distributed table, if one large tuple is across the split boundary, then the execution would fail and generate core.
The fix here is to handle this specific case. More explanations please read the comments.

HAWQ-35. Handle a case when a large tuple across split boundary

---

README.md

Add introduction information about Apache HAWQ in README file.

HAWQ-143. Add informations in Apache-HAWQ README.md

---

tools/bin/hawq_ctl
tools/bin/hawqpylib/hawqlib.py
tools/bin/lib/hawqinit.sh

HAWQ-268. Fix HAWQ activate standby fails

---

src/backend/cdb/cdbmetadatacache.c
src/include/catalog/pg_proc.h
src/include/catalog/pg_proc.sql
src/include/utils/builtins.h
src/test/regress/data/upgrade20/pg_proc.data

HAWQ-284. Add a udf for new metadata flush strategy testing.

---

src/backend/gpopt/ivy.xml
src/test/regress/expected/partition_full_outer_join.out
src/test/regress/sql/partition_full_outer_join.sql

Handle NULL pointer with partition elimination over full outer join queries.

Bump GPOPT version to 1.617

---

src/backend/commands/tablecmds.c

When the user fires the following query: 
```
alter table redist_test set with (reorganize=true) distributed  randomly;
```
The intention of the user is to force redistribute the tuple so that there is no skew. 
Under the hood, GPDB first creates a temp table via CTAS and then replaces the table with the temp table. Given that source table and the temp table are both random, Orca says random satisfies random and therefore no tuple relocation via motions is needed. This changes the expected behavior. 
The fix inside Orca is quite extensive, so the immediate stop gap is to fall back to the planner when we execute the CTAS.
@xinzweb @hsyuan  please take a look

Fallback to planner for command: ALTER TABLE SET DISTRIBUTED BY

---

tools/bin/gppylib/operations/filespace.py
tools/bin/hawqfilespace

For example:
hawq filespace --movefilespace=cdbfast_fs_a --location=hdfs://gphd-cluster/cdbfast_fs_a/

HAWQ-351. Add movefilespace option to hawq filespace

---

tools/bin/hawq_ctl
tools/bin/lib/hawqinit.sh

Fix OS version detect for centos/redhat/mac/ubuntu.
Fix some minor init script issues.

HAWQ-235. Fix init issues on centos7.

---

doc/src/sgml/ref/alter_database.sgml
doc/src/sgml/ref/create_database.sgml
src/backend/commands/dbcommands.c
src/backend/utils/init/postinit.c
src/test/regress/input/hcatalog_lookup.source
src/test/regress/output/hcatalog_lookup.source

@shivzone @hornn @kavinderd @GodenYao

HAWQ-369. Hcatalog as reserved name.

---

tools/bin/hawq_ctl

Tested multinodeparallel, tincmisc, sanity.

HAWQ-494. Add checks to standby start/init

---

src/backend/commands/tablecmds.c

fix pointer dereferrence check issue

HAWQ-508. Fix pointer check issue in coverity

---

src/backend/commands/copy.c

HAWQ-532. Optimise vseg number for copy to statement.

---

src/backend/access/parquet/parquetam.c
src/backend/cdb/dispatcher.c
src/backend/tcop/pquery.c
src/backend/utils/misc/faultinjector.c
src/include/utils/faultinjector.h
tools/bin/gppylib/programs/clsInjectFault.py
tools/bin/hawqpylib/programs/clsInjectFault.py

Add fault injection test cases for QE side.

HAWQ-572. Add fault injection test cases for QE side

---

src/backend/utils/misc/guc.c

1. Change seg_max_connections from 1280 to 3000
2. since gp_enable_column_oriented_table is not used, remove the guc value

remove gp_enable_column_oriented_table and change default seg_max_connections default value

---

tools/bin/hawq_ctl
tools/bin/hawqconfig
tools/bin/hawqpylib/hawqlib.py
tools/doc/gpssh-exkeys_help

1. Let 'hawq config' can deal with xml file which do not have a pretty format.
2. Minor typo fix to help message.

HAWQ-651. Enhance update property values in xml file

---

src/backend/cdb/cdbexplain.c
src/include/cdb/cdbexplain.h

output of explain analyze is different between one QE and multiple QE, we should unify the output format.

HAWQ-673. Unify out put of explain analyze.

---

src/bin/Makefile

Not sure why it was deleted in a previous commit.

HAWQ-777 Add back gpfdist

---

src/backend/gpopt/translate/CTranslatorQueryToDXL.cpp

Remove unreachable (stale) code paths in the Algebrizer.
@hsyuan @oarap @d please check.

HAWQ-857. Remove dead code in the Algebrizer

---

.travis.yml

From 25min -> 17min: https://travis-ci.org/xunzhang/incubator-hawq/builds/140718129

HAWQ-873. improve checking time for .travis.yml

---

depends/libyarn/test/function/TestLibYarnClientC.cpp

HAWQ-891. Fix functiontest build error

---

src/backend/cdb/cdbpartition.c

RelationGetRelationName should be RelationGetRelid

HAWQ-1032. Fix bug of wrong parameter in GpPolicyFetch.

---

pxf/build.gradle
pxf/pxf-api/src/main/java/org/apache/hawq/pxf/api/BasicFilter.java
pxf/pxf-api/src/main/java/org/apache/hawq/pxf/api/FilterParser.java
pxf/pxf-api/src/main/java/org/apache/hawq/pxf/api/LogicalFilter.java
pxf/pxf-api/src/test/java/org/apache/hawq/pxf/api/FilterParserTest.java
pxf/pxf-hbase/src/main/java/org/apache/hawq/pxf/plugins/hbase/HBaseFilterBuilder.java
pxf/pxf-hbase/src/test/java/org/apache/hawq/pxf/plugins/hbase/HBaseFilterBuilderTest.java
pxf/pxf-hive/src/main/java/org/apache/hawq/pxf/plugins/hive/HiveAccessor.java
pxf/pxf-hive/src/main/java/org/apache/hawq/pxf/plugins/hive/HiveDataFragmenter.java
pxf/pxf-hive/src/main/java/org/apache/hawq/pxf/plugins/hive/HiveFilterBuilder.java
pxf/pxf-hive/src/main/java/org/apache/hawq/pxf/plugins/hive/HiveORCAccessor.java
pxf/pxf-hive/src/test/java/org/apache/hawq/pxf/plugins/hive/HiveFilterBuilderTest.java

Signed-off-by: Leslie Chang <hi.lesliechang@gmail.com>

HAWQ-964. Support for OR and NOT Logical Operators

---

tools/bin/hawqregister

HAWQ-1144. Put partition multi-level check ahead of hdfs file check.

---

tools/bin/hawqregister

HAWQ-1171. Add UDF check before register

---

src/test/feature/ManagementTool/test_hawq_register_usage2_case1.cpp

cc @ictmalili @linwen @interma @xunzhang pls review. thanks.

HAWQ-1221. Add register test case verify bug fix YamlFileNotExist and NonDefaultBucketnum check.

---

src/backend/libpq/be-secure.c
src/backend/libpq/rangerrest.c
src/include/utils/rangerrest.h
src/test/regress/checkinc.py

lnclude:
1. fix core dump while RPS not running
2. fix libcurl write_callback() problem
3. add libcurl timeout (hard-coded 30s temporarily)
4. fix some compile warnings
5. fix make install error: add json.h to checkinc.py
And old PR discuss: https://github.com/apache/incubator-hawq/pull/1058

HAWQ-1226. HAWQ core dump due to enable ranger while RPS is down

---

ranger-plugin/Makefile

HAWQ-1350. Fix ranger-plugin makefile error

---

src/backend/Makefile
src/test/regress/GNUmakefile
tools/bin/Makefile
tools/bin/ext/Makefile
tools/bin/gppylib/Makefile
tools/bin/hawqpylib/Makefile
tools/bin/pythonSrc/PyGreSQL-4.0/setup.py
tools/doc/Makefile
tools/gpnetbench/Makefile

Need to handle pygresql install as it depend on the pre-installed hawq components.

HAWQ-1401. Fix HAWQ make install with DESTDIR.

---

src/bin/gpfdist/Makefile
src/pl/Makefile
src/pl/plr.spec
src/pl/vplr.spec
tools/bin/hawqregister
tools/bin/lib/hawqinit.sh

This was done by amyrazz44, edespino, internma and liming01 intermittently.

HAWQ-1478. Enable hawq build on suse11

---

depends/libhdfs3/src/common/SessionConfig.cpp
src/backend/utils/misc/etc/hdfs-client.xml

@wengyanqing @interma pls feel free to review this pull request, thank you.

HAWQ-1511. Add TDE-related properties into hdfs-client.xml

---

pxf/build.gradle

The files will be installed into /opt/pxf-${project.version} directory.

HAWQ-1496. Add DISCLAIMER, LICENSE and NOTICE files into PXF rpm.

---

src/backend/access/external/fileam.c
src/backend/commands/copy.c
src/backend/executor/execDML.c
src/backend/executor/execMain.c
src/include/access/fileam.h
src/include/access/plugstorage.h
src/include/access/plugstorage_utils.h

Add the external table insert and copy from(write into external table) related feature here.

HAWQ-1566. Include Pluggable Storage Format Framework in External Table Insert

---

src/backend/utils/hash/bloomfilter.c
src/backend/utils/misc/guc.c
src/include/utils/guc.h

HAWQ-1606. Fix "make unittest-check" error and set GUC error.

---

contrib/vexecutor/Makefile
contrib/vexecutor/create_udv.sql.in
contrib/vexecutor/execVScan.c
contrib/vexecutor/vagg.c
contrib/vexecutor/vcheck.c
contrib/vexecutor/veinstall.sh
contrib/vexecutor/vexecutor.c
contrib/vexecutor/vexecutor.h
src/backend/executor/execProcnode.c
src/include/executor/executor.h
src/test/feature/catalog/ans/type_sanity.ans
src/test/feature/catalog/sql/type_sanity.sql

Co-authored-by: 'Shujie Zhang <shzhang@Shujie-Zhangs-MacBook-Pro.local>'

HAWQ-1619. Fix Vectorized Execution bugs

---

depends/libyarn/src/libyarnclient/ApplicationClient.cpp
depends/libyarn/src/libyarnclient/ApplicationMaster.cpp

Fix compile issue due to unsupported syntax in libyarn on osx 10.11

HAWQ-1636. Fix compile apache hawq failure due to unsupported syntax in libyarn on osx 10.11

---

pxf/build.gradle
pxf/gradle/wrapper/gradle-wrapper.properties
pxf/gradlew
pxf/pxf-service/src/main/java/org/apache/hawq/pxf/service/rest/VersionResource.java
pxf/pxf-service/src/main/webapp/WEB-INF/web.xml

- Removes code generation from PXF to enable IntelliJ code intelligence
- Upgrade gradle to version 4.9

HAWQ-1645. Remove code generation from PXF and upgrade gradle version

---

pxf/gradle.properties

Improve PXF compilation time by running gradle in parallel and using gradle daemon

Run gradle build in parallel

---

pxf/pxf-service/src/test/java/org/apache/hawq/pxf/service/utilities/SecuredHDFSTest.java

Fixes compilation issue in Java 7 for SecureHDFSTest

HAWQ-1650. Fix compilation issue in Java 7

---

contrib/Makefile
contrib/exthdfs/exthdfs.c
contrib/orc/cwrapper/Makefile
contrib/orc/cwrapper/format/Makefile
depends/libyarn/src/libyarnclient/ApplicationClient.cpp
depends/libyarn/src/libyarnclient/ApplicationMaster.cpp

Raise this PR for hour
fix misc issues before orc format support, including typos, bugs, license

fix misc issues before orc format support

---

src/test/feature/cloudtest/sql/normal/all.sql
src/test/feature/cloudtest/sql/normal/before_normal.sql
src/test/feature/cloudtest/sql/parallel/before_parallel.sql
src/test/feature/cloudtest/sql/parallel/parallel.sql
src/test/feature/cloudtest/test_cloud.cpp
src/test/feature/cloudtest/test_cloud.h
src/test/feature/cloudtest/test_cloud.xml
src/test/feature/lib/parse_out.cpp
src/test/feature/lib/parse_out.h
src/test/feature/lib/psql.cpp
src/test/feature/lib/psql.h
src/test/feature/lib/sql_util.cpp
src/test/feature/lib/sql_util.h
src/test/feature/lib/sql_util_parallel.cpp
src/test/feature/lib/sql_util_parallel.h
src/test/feature/lib/sqlfile-parsebase.cpp
src/test/feature/lib/sqlfile-parsebase.h

Add test for cloud environment support

HAWQ-1689. Add test for cloud environment support

---

src/backend/cdb/cdbdatalocality.c

add comment for enforce virtual segment number.
which is the ultimate factor to determine virtual segment number.

HAWQ-1755. add comment for enforce virtual segment number.

---

src/backend/cdb/cdbdatalocality.c

https://issues.apache.org/jira/browse/HAWQ-1756

HAWQ-1756. add comment for struct TargetSegmentIDMap.

---

depends/dbcommon/src/dbcommon/common/vector.cc
depends/dbcommon/src/dbcommon/common/vector/struct-vector.h
depends/dbcommon/src/dbcommon/function/agg-func.cc
depends/dbcommon/src/dbcommon/function/func.cc
depends/dbcommon/src/dbcommon/testutil/vector-utils.h
depends/dbcommon/src/dbcommon/type/type-kind.h
depends/dbcommon/test/unit/function/test-agg-func-has-no-group-by.cc
depends/dbcommon/test/unit/function/test-agg-func-small-scale.cc
depends/dbcommon/test/unit/function/test-agg-func.cc
depends/storage/src/storage/format/orc/orc-format-reader.cc
depends/storage/src/storage/format/orc/orc-format-writer.cc
depends/storage/src/storage/format/orc/vector.h
depends/storage/test/unit/format/test-orc-vector.cc

add disk memory usage for agg function to deal with OOM in memory intensive operator
add intermediate output frist

HAWQ-1767. Add TypeKind for aggregate function intermediate output
