src/backend/cdb/workermgr.c

Add code to check interrupts when dispatcher waiting job finish.

HAWQ-26. Check cancel signal when Dispatcher waiting for job finish

---

src/backend/catalog/gp_toolkit.sql.in

Update the gp_toolkit.sql.in to skip hcatalog database when calculating the sizes of database.

HAWQ-10. Skip hcatalog database when calculating the sizes of databases

---

src/backend/nodes/copyfuncs.c

Add error table information when copying an External Scan Operator.

HAWQ-32. Add a copy function for ResultRelSegFileInfo

---

tools/bin/hawq_ctl

This line is useless and will make hawq init error in some cases. So just delete it. As test, after the change, hawq init goes well.

HAWQ-69. Fix HAWQ init issue when HDFS HA enabled.

---

src/backend/utils/misc/etc/hawq-site.xml
src/backend/utils/misc/etc/template-hawq-site.xml

Since we have changed the GUC design for RM. Now we need to update the related GUC names in hawq-site.xml.
For example:
hawq_resourcemanager_server_type --> hawq_global_rm_type.

HAWQ-83. Rename resource manager's GUC names in hawq-site.xml.

---

src/backend/cdb/cdbdatalocality.c

Format the log of datalocality
"datalocality ratio: 0.000; virtual segments number: 1, different host number: 1, segment number per host(avg/min/max): (1/1/1); segments size(avg/min/ max): (0.000/0/0); segments size with penalty(avg/min/max): (0.000/0/0); continuity(avg/min/max): (0.000/0.000/0.000)."
need to formatted to
"data locality ratio: 0.000; virtual segment number: 1; different host number: 1; virtual segment number per host(avg/min/max): (1/1/1); segment size(avg/min/ max): (0.000/0/0); segment size with penalty(avg/min/max): (0.000/0/0); continuity(avg/min/max): (0.000/0.000/0.000)."

HAWQ-115. Format the log of datalocality

---

getversion

Previously version number "2.0.0.0-beta" will cause rpm package fail, so change '-' to '_' .

HAWQ-167. Update HAWQ VERSION to 2.0.0.0_beta for make rpm package.

---

configure
configure.in

Hi,
We have investigated this issue, and we found the root cause is that gcc-4.8 introduced new feature "-faggressive-loop-optimizations". This optimization feature is enabled by default, and it will break variable length array under some condition.
Similar issue can be found from PostgreSQL 9.2. See the following links for detail:
1. http://www.postgresql.org/message-id/14242.1365200084@sss.pgh.pa.us
2. https://gcc.gnu.org/gcc-4.8/changes.html
3. http://pkgs.fedoraproject.org/cgit/postgresql.git/commit/?h=f19&id=2a75d7af27fdf03e875f76f4c272c8435f565d10
So, we just borrow the idea to fix this issue and create a patch. Please review it.
Thanks.

HAWQ-233. Fix HAWQ initialization failed on Centos7

---

src/backend/access/transam/clog.c
src/backend/access/transam/multixact.c
src/backend/access/transam/subtrans.c
src/backend/access/transam/twophase.c
src/backend/access/transam/varsup.c
src/backend/access/transam/xact.c
src/backend/cdb/cdbappendonlystoragewrite.c
src/backend/cdb/cdbpersistentfilesysobj.c
src/backend/commands/dbcommands.c
src/backend/commands/tablecmds.c
src/backend/storage/smgr/smgr.c
src/include/cdb/cdbpersistentstore.h

MirroredLock is no use in hawq because there is no segment mirroring, and it is not used by master mirroring which uses xlog directly.
The reason why we need to remove it is: in some scenarios the request order of this lock and CheckpointStartLock may cause deadlock.

HAWQ-241: Remove  MirroredLock related codes

---

src/backend/cdb/cdbmetadatacache.c
src/backend/cdb/cdbmetadatacache_process.c
src/backend/cdb/cdbvars.c
src/backend/utils/misc/guc.c
src/include/cdb/cdbvars.h

HAWQ-265. Change metadata share memory flush strategy to prevent out of share memory problem when create too many hdfs_file.

---

tools/bin/lib/hawqinit.sh

If hawq master start before standby, in some cases standby will do recovery, this will cause master can't connect to standby to do "Synchronized" check. So we will start standby first and sleep 5 seconds, then start master. This should avoid most of the "Synchronized" failues.
Error message is:
[' Not Synchronized | Connection error | 2015-12-23 20:52:20-08 | Master mirroring connect failed for entry db. Master unable to connect to test5 with options host=test5 port=20000 : FATAL:  the database system is in recovery mode \n',

HAWQ-268. Start standby node before master node  while doing hawq init standby

---

src/backend/commands/tablecmds.c
src/backend/parser/gram.y
src/test/regress/output/exttab1_optimizer.source

writable external table is used for export data in hawq to others.
In hawq1.x default is on all, which is deprecated in hawq2.x
we support this feature by using on number instread of on all.

HAWQ-293. Enable writable external table to support on number syntax.

---

src/backend/cdb/cdbdatalocality.c

when rollback happens, hdfs block length may increase and longer than metadata logic length.

HAWQ-298. Double check hdfs length longer than metadata logic length.

---

src/backend/cdb/cdbmetadatacache_process.c
src/backend/utils/misc/guc.c

HAWQ-295. New metadata flush strategy remove 1 entry every time flush due to flush condition wrong.

---

src/backend/cdb/cdbbufferedread.c

"real_fileLen" should be int64 as "fileLen" is a int64 number and "bufferedRead->largeReadPosition" is also a int64 number.
According to the code, a int64 number is changed to int32 which make the number wrong.
See more in https://issues.apache.org/jira/browse/HAWQ-314

HAWQ-314. Fix AO Read when a segment file larger than 4TB

---

src/backend/executor/execMain.c
src/backend/utils/init/globals.c
src/backend/utils/misc/guc.c
src/include/miscadmin.h
src/test/regress/expected/parquet_compression.out
src/test/regress/sql/parquet_compression.sql

The fix tries to assign query memory quota to memory intensive operators in a conservative manner.
At present, we give GUC hawq_re_memory_quota_allocation_ratio a default value 0.5. This needs to be tuned later with more tests.

HAWQ-300. Fix out of memory during loading large volume data on large cluster with YARN mode

---

src/backend/catalog/Makefile
src/backend/catalog/gp_toolkit.sql.in
src/bin/Makefile
src/bin/gpoptutils/Makefile
src/bin/gpoptutils/gpoptutils.c
tools/bin/minirepro

As a Database User, I should be able to dump the DDL and Statistics Information for a given query so I don't have to dump a large GPDB file.
GIVEN I am a Database User
WHEN I run minirepro database-name -q sql-file-name -f output-file-name
THEN I should get the DDL and statistics info for the tables and views accessed in that query

HAWQ-324. Add minirepro management utility

---

src/backend/utils/misc/guc.c

After performance test, we decide to change default net_disk_ratio from 3.0 to 1.0. It'll reach better performance on large dataset or complex query.

HAWQ-336. Set default net_disk_ratio to 1.0.

---

tools/bin/generate-greenplum-path.sh

Fix following environment only for OSX:
Remove ext/python/bin from PATH to avoid using the Python version from HAWQ.
Remove the library path lib/python/pygresql from PYTHONPATH.
Remove ext/python/lib from DYLD_LIBRARY_PATH.
@hornn @radarwave

Fix 'hawq' issue for OSX after Python is removed.

---

NOTICE

Based on feedback I saw on some other Apache Podling votes I noticed that our NOTICE file had not been updated for 2016.  
Note: this does *not* update copyright dates on some other components such as:
> HBase
> Apache HBase
> Copyright 2007-2015 The Apache Software Foundation
Because these copyrights are based on the versions of our dependencies and these should be updated when we update to newer versions that themselves have updated copyrights - I think.
It also does not update:
> Portions Copyright (c) 2014-2015, Pivotal Inc.
Because all changes since donating the code to Apache are under the Apache ICLA agreement and thus Copyright to Apache.

HAWQ-342. Update copyright to 2016

---

src/backend/access/transam/xact.c

As we removed CHECKPOINT_START_LOCK , we need to set fault_injector here, then we can test it.

HAWQ-290. Add faultinjector for test.

---

src/backend/utils/misc/guc.c

Data locality ratio for TPCH query(such as Q2) in SFO is low when some machines are down.
The reason for this is that we change net_disk_ratio to 1.0 which leads to we prefer the virtual segment with minimum allocated size plus current split size, but not LOCAL!
To prevent this happens we need to enlarge net_disk_ratio to 1.01. Then if the current size of two vsegs are almost the same, we can choose the LOCAL one.

HAWQ-366. Analyse data locality ratio for TPCH query in SFO.

---

pxf/build.gradle
pxf/gradle.properties
pxf/pxf-service/src/main/java/org/apache/hawq/pxf/service/rest/VersionResource.java
pxf/pxf-service/src/test/java/org/apache/hawq/pxf/service/rest/VersionResourceTest.java

$ curl -i http://localhost:51200/pxf/ProtocolVersion
HTTP/1.1 200 OK
Server: Apache-Coyote/1.1
Content-Type: application/json
Transfer-Encoding: chunked
Date: Sat, 23 Jan 2016 00:01:31 GMT
{ "version": "v14"}

HAWQ-340. Make getVersion API return JSON format.

---

src/backend/commands/analyze.c
src/backend/commands/copy.c
src/include/commands/vacuum.h

Root cause analysis shows that the hang of concurrent workload is in three folds:
Most of the queries lock relations at first and then allocate resource for it, while analyze (either manually or automatically triggered) allocate resource at first and then lock relation. This may lead to deadlock between relation lock and query resource with concurrent queries.
Some of the queries may do query resource allocation multiple times, i.e., SRI/COPY which triggers automatic statistics collection. They do not return query resource as soon as some of the sub tasks are done for the query.
For example, SRI allocate resource for insert itself, do insertion, return query resource for insertion, allocate resource for automatically triggered analyze, do analyze, return query resource for analyze; while …

HAWQ-372. Fix single row insert and COPY hang in high concurrent workloads

---

src/backend/access/parquet/parquetam.c
src/backend/cdb/cdbparquetfooterprocessor.c
src/backend/cdb/cdbparquetfooterserializer.c

Move the parquetMeta struct construction from two callers to one place, and avoid memory leak.

HAWQ-407. Fix memory leak in parquet metadata processing for reading table with data

---

src/test/regress/pg_regress.c

initfile  and expected_statuses_file are constant string and should not be freed

HAWQ-440. Fix bug in pg_regress of commit HAWQ-432.

---

tools/bin/hawq_ctl

Currently if we do 'hawq stop master/standby' while master/standby already in stop stage, we will recognize the stop action is failed.
Now we will recognize they are success.
Passed sanity and multinodeparallel tests.

HAWQ-454. 'hawq stop' should return true if master/standby already stopped

---

tools/bin/hawq_ctl
tools/bin/hawqpylib/hawqlib.py

1. We should check if HAWQ master is doing recovery.
2. When doing hawq master stop, check if there any existing connections. Master stop abort if use smart stop, give warning if use fast stop.
3. Hawq start/stop use 600 seconds as default timeout.

HAWQ-467. Add checks to HAWQ master start/stop

---

src/backend/commands/copy.c

GetFileSplitsOfSegment should be called after appendonly_beginscan

HAWQ-477. Copy table to file do not real execute for lineitem.

---

src/backend/commands/analyze.c
src/backend/commands/copy.c

targetPolicy may be null in initialization
copy case should consider parquet code branch

HAWQ-484. Fix bug in gpcopy and pgdump bug.

---

configure
configure.in
src/backend/access/external/hd_work_mgr.c
src/backend/access/external/pxfanalyze.c
src/backend/access/external/pxfmasterapi.c
src/backend/catalog/hcatalog/externalmd.c
src/include/pg_config.h.in

- Uses new path `json-c/json.h` rather than `json/json.h`
Signed-off-by: Xin Zhang <xzhang@pivotal.io>

HAWQ-479: Update JSON-C from 0.6 to 0.12

---

src/backend/postmaster/walsendserver.c

Here just fixed the timeout problem. The auto re-sync standby functionality will be implemented as a feature in the future.

HAWQ-504. Crash when WALSendServer and standby connection timeout

---

src/backend/executor/execDML.c
src/backend/executor/execMain.c
src/backend/executor/execUtils.c
src/backend/executor/nodeDML.c
src/backend/gpopt/ivy.xml
src/backend/gpopt/translate/CTranslatorDXLToPlStmt.cpp
src/backend/gpopt/translate/CTranslatorRelcacheToDXL.cpp
src/backend/gpopt/utils/COptTasks.cpp
src/backend/nodes/copyfuncs.c
src/backend/nodes/outfast.c
src/backend/nodes/outfuncs.c
src/backend/nodes/readfast.c
src/backend/utils/misc/guc.c
src/include/executor/execDML.h
src/include/gpopt/translate/CTranslatorUtils.h
src/include/nodes/execnodes.h
src/include/nodes/plannodes.h
src/include/utils/guc.h
src/test/regress/expected/goh_partition.out
src/test/regress/expected/gpsql_alter_table_optimizer.out
src/test/regress/expected/insert_optimizer.out
src/test/regress/sql/goh_partition.sql

This PR adds a new GUC for GPORCA: `optimizer_parts_to_force_sort_on_insert `, which implies the minimum number of partitions required to force sorting tuples during insertion in an append only row-oriented partitioned table.
For AO with small number of partitions that is less than the GUC value of `optimizer_parts_to_force_sort_on_insert `, sort is not needed for insert. For a relatively large number of partitions that is larger or equal to `optimizer_parts_to_force_sort_on_insert `, sort is needed.  
Sort during inserting on append only row oriented partitioned tables is disabled by default, with the default GUC value as INT_MAX.
This requires GPORCA version number >= 1.623

HAWQ-404. Add sort during INSERT of append only AO partition tables

---

src/backend/access/external/hd_work_mgr.c
src/backend/access/external/pxfutils.c
src/backend/utils/adt/pxf_functions.c
src/bin/gpfusion/gpbridgeapi.c
src/include/access/pxfutils.h

We were carrying character buffer size of 64k over stack which was unnecessary because it was used in method pxfutils.process_request only, moved it to local variable.

 HAWQ-599. Fixed coverity issues.

---

tools/bin/gppylib/util/ssh_utils.py
tools/bin/gpscp
tools/bin/hawq_ctl
tools/bin/hawqconfig
tools/bin/hawqpylib/HAWQ_HELP.py
tools/bin/hawqpylib/hawqlib.py
tools/doc/gpscp_help

Currently Activate standby operations uses 'hawq config' to update hawq-site.xml. However, in case any of the HAWQ host is down, the operation fails while syncing up the configuration. In case of big clusters, there can be few segment hosts which are down and that will prohibit activating standby.
Thus, introduced a new flag in hawq config to ignore bad hosts and continue syncing files on hosts on which test ssh is successful

HAWQ-617 Add option to skip syncing configuration files

---

depends/libhdfs3/src/rpc/RpcClient.cpp

1) The problem is caused by the wrong refs in RpcChannelImpl class, so it run a dead loop when process exiting. I suspect it is caused by the exception thrown by RpcClientImpl::getChannel(), which already addRef(), but doesn't call close() when exception occurs.
2) This problem cannot be fixed by enable SIGNAL handle before calling libhdfs functions, because the clean up process is already called when dead loop occurs.

HAWQ-635. QE process does not exit in libhdfs

---

tools/sbin/gpcheck_hostdump

Tested config files in '/etc/security/limits.d', it works well with different config file and different user if defined user domain.

HAWQ-636. hawq check include /etc/security/limits.d

---

src/backend/optimizer/plan/planner.c

Root cause analysis:
1. It uses exec_parse_message and exec_bind_message and allocate query resource twice in parse and bind phases accordingly when using jdbc to call the function: SELECT public.fn_debug(). Thus query resource is allocated twice in function call through jdbc.
2. It uses exec_simple_query and allocate query resource there only once when using psql/libpq to call the function: SELECT public.fn_debug().
The resolution is to do not allocate query resource in parse, and only allocate query resource in bind.

HAWQ-738. Allocate query resource twice in function call through jdbc

---

src/backend/Makefile
src/backend/bootstrap/.gitignore

`bootstrap_tokens.h` isn't a file that exists anymore; was causing `make distprep` to fail

HAWQ-543. Remove references to bootstrap_tokens.h

---

tools/bin/gpcheck

When YARN HA is enabled in HDP, the following four params don't actually exist. However, hawq check has been hard-coded to look for them, causing a failure. 
yarn.resourcemanager.address.rm1
yarn.resourcemanager.address.rm2
yarn.resourcemanager.scheduler.address.rm1
yarn.resourcemanager.scheduler.address.rm2
*Correct params:*
yarn.resourcemanager.hostname.rm1
yarn.resourcemanager.hostname.rm2
yarn.resourcemanager.scheduler.address (apparently, there is no rm1/rm2 specified for scheduler)

HAWQ-871. HAWQ CHECK looking for wrong YARN HA parameters

---

tools/bin/gpcheck

When kerberos is enabled, we run 'hawq check' without '--kerberos' option,
it will give 'global name 'hadoop' is not defined' error.

HAWQ-872  Fix HAWQ check fails when kerberos is enabled

---

src/test/feature/Makefile
src/test/feature/lib/Makefile

This pull request contains below modifications:
1. Fix a bug in building UDF/lib.
2. Refactor feature test make system to avoid duplicate compiles.
3. Split generating `feature-test` binary into generating objects and linking. Optimize compiling time in parallel mode.

HAWQ-911. Optimize and refactor makefiles for feature test framework.

---

src/backend/access/external/fileam.c
src/backend/access/external/pxfheaders.c
src/backend/access/external/url.c
src/backend/executor/nodeExternalscan.c
src/bin/gpfusion/gpbridgeapi.c
src/include/access/extprotocol.h
src/include/access/fileam.h
src/include/access/pxfheaders.h
src/include/access/url.h

This commit makes the necessary modifications to the HAWQ side of
the codebase to add a list of indices of projected columns

HAWQ-927. Pass ProjectionInfo data to PXF

---

src/backend/resourcemanager/resourcebroker/resourcebroker_LIBYARN_proc.c
src/bin/gpcheckhdfs/gpcheckhdfs.c
tools/bin/gpcheck
tools/bin/hawq_ctl
tools/bin/hawqfilespace

This fix remove the check of "postgres" for kerberos service name if HAWQ is running with kerberos enable.
So that, customers can replace "postgres" with a different service name.
If user want to use a different name, below property/value should be added into hawq-site.xml,
otherwise "postgres" is used. 
<property>
<name>krb_srvname</name>
<value>gpadmin</value>
</property>
Please review, thanks!

HAWQ-845. Parameterize kerberos principal service name for HAWQ

---

src/backend/catalog/aclchk.c
src/backend/parser/parse_relation.c
src/backend/utils/misc/guc.c
src/include/utils/acl.h
src/include/utils/guc.h

Along with HAWQ-1002. Implement a switch in hawq-site.xml to configure whether use Ranger or not for ACL.
I create a GUC enable_ranger to control whether hawq use ranger to do acl control.
Also, when client doing a acl check with ranger enabled, typically a select statement needs the privilege to access the range table, we call pg_rangercheck() to determine the whether access is allowed. 
The content of pg_rangercheck() is just return ACLCHECK_OK temporarily, and should be changed to a call to ranger restful service in future.

HAWQ-1001. Implement HAWQ user ACL check through Ranger.

---

pom.xml

Avoid maven license check for the pgcrypto code since it comes from upstream postgres.

HAWQ-1007. Add the pgcrypto code into hawq

---

src/pl/plr.spec

Previously it will get install to /usr/local/hawq, but it's possible that hawq is installed into '/usr/local/hawq_2_0_1_0.
@paul-guo- @xunzhang

HAWQ-1067. Append hawq version number to plr-hawq rpm pakcage install location

---

depends/thirdparty/gporca.commit
depends/thirdparty/gpos.commit
src/backend/gpopt/CGPOptimizer.cpp
src/backend/gpopt/gpdbwrappers.cpp
src/backend/gpopt/translate/CTranslatorQueryToDXL.cpp
src/backend/gpopt/utils/COptTasks.cpp
src/include/gpopt/utils/COptTasks.h
src/test/regress/expected/errors.out
src/test/regress/expected/horology.out
src/test/regress/sql/errors.sql
src/test/regress/sql/horology.sql

Below is the matching PR explaination from GPDB.
In COptTasks::PplstmtOptimize, we print exception message from context using elog::ERROR. Because orca / gpos enhanced to rethrow exception, we were not executing this code.
In this PR, we catch the exception and print the message as warning. After printing, we throw the exception and abort the plan generation in CGPOptimizer::PplstmtOptimize.
We can't use elog::ERROR because it will do sigjmp to PostgresMain and hence result in memory leak. Also since there is no easy way to carry the message in CException, as an initial implementation we decided to print as warning.
There is a story to handle this case properly in backlog : https://www.pivotaltracker.com/story/show/118056737
Orca related changes : …

[#126526845] Port recent changes from gpdb for hawq

---

.travis.yml

* Remove the "brew tap brona/iproute2mac" command as an update to "brew"
has revealed an issue with the "tap".  We will be able to install the
component (iproute2mac) directory from the main repository.

HAWQ-1150. Fix Travis build issue (brona/iproute2mac).

---

contrib/hawq-ambari-plugin/build.properties
pxf/gradle.properties

Update PXF (3.1.0), HDB Ambari plugin (2.1.0.0) and default Ambari default stack version (HDP-2.5).

HAWQ-1141: Bump PXF and default HDB Stack version.

---

src/backend/utils/cache/relcache.c

Fixed below warning:
WARNING:  relcache reference leak: relation "pg_class" not closed
The test case exists when the meta tuple in pg_class in invalid.
This bug also exists in postgreSQL, although it doesn't called for some reason.

HAWQ-1149. Fixed relcache reference leak when pg_class tuple is invalid

---

src/backend/catalog/aclchk.c
src/backend/parser/parse_relation.c
src/backend/utils/misc/guc.c
src/include/parser/parse_relation.h
src/include/utils/acl.h
src/include/utils/guc.h

This pr includes :
HAWQ-1001. Implement HAWQ basic user ACL check through Ranger.
HAWQ-1002. Implement configuration GUC related to Ranger.
HAWQ-1003. Implement bached ACL check through Ranger.
when GUC enable_ranger is ON, we will use ranger_acl_check to determine where user has the permission to query the data.

HAWQ-1002. Implement configuration GUC related to Ranger.

---

tools/bin/lib/hawqinit.sh

Add single quote to ROLENAME, so it's capital sensitive. 
Add option '-v ON_ERROR_STOP=on' to psql client, so it will fail for each sql queries in the sql file but not only the last query.

HAWQ-1227. Fix hawq init fails when user name with a capital.

---

src/backend/utils/misc/guc.c

change the default RPS RESTFUL service suffix to rps

HAWQ-1243. Add suffix name for ranger restful service.

---

src/pl/plperl/GNUmakefile

Please see HAWQ-1277 for additional details.
This fix was originally backported from PostgreSQL to the Greenplum DB master branch a year ago by Heikki Linnakangas<https://github.com/hlinnaka> (Original PostgreSQL committer Andrew Dunstan <andrew@dunslane.net<mailto:andrew@dunslane.net>>):
https://github.com/greenplum-db/gpdb/commit/f493756a5ac8a90ff1d5e3b84f38a153c9f80b9c#diff-97d34e5e3684082069b6c85876df9107
See earlier discussion on this on pgsql-hackers, message-id
9B946296-A2EB-4B45-A190-153F06662F8B@kineticode.com. We'd get this fix
eventually as we merge with later PostgreSQL versions, but let's make life
easier for people hitting this issue now.
This is a backpatch of the following upstream commit, sans the MSVC build
parts, as I have no environment to test that and we don't …

HAWQ-1277. Fix build problem on CentOS 7, with --with-plperl.

---

src/backend/catalog/namespace.c
src/backend/tcop/postgres.c
src/include/catalog/namespace.h

After HAWQ-1279 is done, current schema is no cached in current session.
But it cause too many calls of namespace check to send in run \d , most of them are unnecessary.
```
\d:
select version()
SELECT n.nspname as \"Schema\",\n  c.relname as \"Name\",\n  CASE c.relkind WHEN 'r' THEN 'table' WHEN 'v' THEN 'view' WHEN 'i' THEN 'index' WHEN 'S' THEN 'sequence' WHEN 's' THEN 'special' END as \"Type\",\n  pg_catalog.pg_get_userbyid(c.relowner) as \"Owner\"\nFROM pg_catalog.pg_class c\n     LEFT JOIN pg_catalog.pg_namespace n ON n.oid = c.relnamespace\nWHERE c.relkind IN ('r','v','S','')\n      AND n.nspname <> 'pg_catalog'\n      AND n.nspname <> 'information_schema'\n      AND n.nspname !~ '^pg_toast'\n  AND pg_catalog.pg_table_is_visible(c.oid)\nORDER BY 1,2;
recomputeNamespacePath() …
```

HAWQ-1286. Reduce unnecessary calls of namespace check when run \d

---

src/backend/catalog/aclchk.c

When we do ranger check of query "create temp table", we need to PASS privilege "TEMP" to RPS instead of "CREATE_TEMP". Or RPS can not recognise it.

HAWQ-1291. Fix the name of privilege when create temp table.

---

src/backend/storage/ipc/ipc.c

(1) From the bt in the core file, it seems that SuppressPanic is true, we still report panic even at process exist function. We should suppress the panic if there is no side effect. 
(2) Now hawq stop utility stop standby after master stopped successfully or failed to stop with 10 minutes timeout, so it seems no need to change.

HAWQ-1338. Fixed writer process doesn't exit nicely in some case

---

.travis.yml

* Display installed brew components and version after brew update.
* Remove libevent installation.
I am not sure this will fix the Travis build issue.  This will give us insight to what components are installed in the base brew installation.

HAWQ-1336. Travis CI "brew" updates

---

.travis.yml

The latest Travis CI OS X builds are failing (https://travis-ci.org/apache/incubator-hawq/builds/202425654) because "pip" command is not found.  This change will install it.
Error:
$ sudo pip install pycrypto
sudo: pip: command not found

HAWQ-1343. - Install pip and minor formatting change.

---

contrib/jenkins/HAWQ-build-pullrequest.sh
contrib/jenkins/HAWQ-rat.sh

While working on the Apache Jenkins projects supporting HAWQ, I noticed the scripts are not checked in anywhere. This PR captures their contents.
The following Jenkins build scripts are being stored for easier
maintenance.
* HAWQ-build-pullrequest
* HAWQ-rat

HAWQ-1364. Store Apache Jenkins build scripts.

---

README.md

Updating embedded external CI status images to include the HAWQ-rat project. Additionally, update documentation link to point at open source doc set.
The visible changes to the README.md can be seen here: https://github.com/edespino/incubator-hawq/tree/HAWQ-1369
reviewers: @paul-guo- @radarwave

HAWQ-1369. Update for RAT status and external doc link in README.md

---

contrib/hawq-ambari-plugin/src/main/resources/utils/add-hawq.py

The HAWQ Ambari is only registering systems running CentOS/RHEL 6 platforms. We have identified this minor fix which will register CentOS/RHEL 7 systems as well.

HAWQ-1387. Add support for CentOS/RHEL 7 in HAWQ Ambari plugin.

---

config/programs.m4
config/tomcat.m4
configure

* The FLEX configure snippet came from Postgres upstream in the form
of two commits (see below).
* Misc change: commit tomcat version check for Mac OSX platform using
brew. This change was out of sync with generated "configure" script.
commit 7d7b129277eb545286aecf29ec22b5bb7fdf46bd
Author: Tom Lane <tgl@sss.pgh.pa.us>
Date:   Mon May 2 11:18:10 2016 -0400
Fix configure's incorrect version tests for flex and perl.
awk's equality-comparison operator is "==" not "=".  We got this right
in many places, but not in configure's checks for supported version
numbers of flex and perl.  It hadn't been noticed because unsupported
versions are so old as to be basically extinct in the wild, and because
the only consequence is whether or not a WARNING flies by during
configure.
Daniel Gustafsson noted …

HAWQ-1397. Support Flex versions 2.6 and above.

---

GNUmakefile.in
contrib/Makefile
contrib/hawq-package/build_hawq_rpm.sh
contrib/hawq-package/make_rpm_tarball.sh
pxf/Makefile
ranger-plugin/scripts/build_ranger_rpm.sh

This fix included:
1) Fixed HAWQ_RELEASE_VERSION for rpm tarball.
2) Make sure distclean delete all the rpm artifacts.
3) Added some log output.

HAWQ-326. Fix specified HAWQ_RELEASE_VERSION for rpm build.

---

src/backend/access/transam/xact.c
src/backend/access/transam/xlog.c
src/backend/utils/init/flatfiles.c
src/backend/utils/resowner/resowner.c
src/include/utils/resowner.h

(1) Add TopResourceOwner to trace resource used beyond the transaction boundary.
(2) When to auto alloc a new TopResourceOwner for each process?
Generate a singleton TopResourceOwner when setting CurrentResourceOwner to NULL.
(3) If crashed at some code beyond the transaction boundary, we should manually create
a new resource owner, because we don't manually create TopResourceOwner for each process.
(4) When to call ResourceOwnerDelete(TopResourceOwner) automatically for each process?
Register it at on_proc_exit().

HAWQ-1438. Support resource owner beyond transaction boundary

---

src/backend/storage/lmgr/lock.c
src/backend/tcop/postgres.c
src/backend/utils/cache/relcache.c
src/test/feature/catalog/ans/entrydb.ans
src/test/feature/catalog/sql/entrydb.sql
src/test/feature/catalog/test_entrydb.cpp
src/test/feature/full_tests.txt

This reverts the previous fix for HAWQ-512, however to HAWQ-512, it looks like
we could modify the lock related code following gpdb to do a real fix. Those code
was probably deleted during early hawq development.

HAWQ-1455. Wrong results on CTAS query over catalog

---

src/bin/gpfilesystem/hdfs/gpfshdfs.c

`elog` statements attribute errors to wrong function.

HAWQ-1398. Fixing invalid references in log statements.

---

config/maven.m4
configure

The Travis CI build is failing as the Apache Maven 3.5.0 check fails to match the "3" major version check.  This PR simplifies the check.

HAWQ-1481. Rework Maven "3" major version check.

---

ranger-plugin/admin-plugin/src/main/java/org/apache/hawq/ranger/service/HawqClient.java
ranger-plugin/admin-plugin/src/main/java/org/apache/hawq/ranger/service/RangerServiceHawq.java

In my earlier PR,  *decryptPassword()* is called in the beginning of *lookupResource()*, but *BaseClient* (in ranger lib) also need decrypt password in some situation, decrypt twice will cause a exception.
This PR fixed this issue.

HAWQ-1485. Fix exception of decryptPassword twice in lookupResource()

---

src/backend/utils/misc/guc.c

fix a bug which cause HAWQ debug version failed in initializing.

HAWQ-1458. The maximum value of guc share_input_scan_wait_lockfile_timeout should be greater than the default value.

---

pxf/build.gradle
pxf/resources/META-INF/DISCLAIMER
pxf/resources/META-INF/LICENSE
pxf/resources/META-INF/NOTICE

This adds a LICENSE, DISCLAIMER, and NOTICE to each PXF jar file. As the RPMs scatter files about the system. I have not added them as explicit files in the RPM. We can perform this in a separate Jira if needed.
Reviewers: @radarwave @rvs @huor

HAWQ-1489. Add LICENSE, DISCLAIMER and NOTICE to pxf jar files.

---

README.md

I noticed the Travis CI build status was reporting a failed status (red) even though the master branch build was good (green). This change only reports the Travis CI master build status.
Reviewer: @radarwave @lavjain @interma

HAWQ-1499. Update README.md Travis CI status to report only master branch status.

---

src/backend/access/external/fileam.c
src/backend/access/external/url.c
src/backend/nodes/copyfuncs.c
src/backend/nodes/outfast.c
src/backend/nodes/outfuncs.c
src/backend/nodes/readfast.c
src/include/access/extprotocol.h
src/include/access/filesplit.h
src/include/access/formatter.h
src/include/access/relscan.h
src/include/access/url.h

In this commit, I have add some dependent information needed by the following pluggable storage. 
The info added are mainly about external URI, block location, file splits and formatter action. 
The following two commits on including the pluggable storage in the executor, which rely on these information have already been prepared.

HAWQ-1564. Add Pluggable Storage Dependent Information

---

src/backend/access/external/plugstorage.c
src/include/access/plugstorage_utils.h

Due to some unknown issue (`ERROR: remote component error (0): (libchurl.c:897)`), I could not set up the test environment to verify my fix. 
Please help to apply the patch into your test environment to verify it. Thanks!
@interma @radarwave

HAWQ-1578. Regression Test (Feature->Ranger)Failed

---

tools/bin/hawq

[HAWQ-1582](https://issues.apache.org/jira/browse/HAWQ-1582)
https://github.com/apache/incubator-hawq/blob/037be68ffacdac09dbecef22951ffa97bd9acb4a/tools/bin/hawq#L94
Joining all arguments with space raises this bug when there is space in a argument. For example, argument`'ls -1 | wc -l'` becomes several arguments `'ls', '-1', '|', 'wc', '-l'`, which are feed into `subprocess.Popen`
https://github.com/apache/incubator-hawq/blob/037be68ffacdac09dbecef22951ffa97bd9acb4a/tools/bin/hawq#L41
For example, when executing `hawk ssh -h localhost -e 'ls -1 | wc -l'`, the `gpssh -h localhost -e ls -1 | wc -l` is feed into `subprocess.Popen` as cmd, while cmd is expected to be `gpssh -h localhost -e 'ls -1 | wc -l'`.
[commit](https://github.com/YoungForest/incubator-hawq/commit/9ce5be82dcab0c53ab84817 …

HAWQ-1582. hawq ssh cmd bug when pipe in cmd

---

pxf/pxf-service/src/main/java/org/apache/hawq/pxf/service/UGICache.java
pxf/pxf-service/src/scripts/pxf-env.sh
pxf/pxf-service/src/test/java/org/apache/hawq/pxf/service/UGICacheTest.java

- Updates `PXF_KEYTAB` path to live inside `${PXF_HOME}/conf` and `PXF_PRINCIPAL` to default to gpadmin.
- Fixes nanoseconds to milliseconds conversion in UGICache.

HAWQ-1652. Update PXF keytab path to use PXF_HOME

---

src/backend/cdb/cdbdatalocality.c

location number of external table should less than bucketnum of target table
description:
when load data from external table like 
insert into table from exttable.
bucket number of internal table must be less than location number. but the error message is "can not allocate memory."
This is confused to user, so change it.
issue in jira
https://issues.apache.org/jira/projects/HAWQ/issues/HAWQ-1753?filter=allopenissues

JIRA-1753. add datalocality comments

---

src/backend/cdb/cdbdatalocality.c

max segment number for random table is adjusted by limit of virtual segment number per segment. add comment for it.

HAWQ-1754. add comment for max segment number count for random table.

---

.github/workflows/build.yml
.travis.yml
depends/storage/src/CMakeLists.txt
depends/univplan/src/CMakeLists.txt
src/bin/gpfdist/Makefile

Since building HAWQ on macOS(and also other platform) relies on several
dependency libraries, which are hard to track version via Homebrew, a
prebuilt dependency leave developers free from the tedious work.
Such process is easy to maintain and verify via GitHub Action. The
workable workflow file also indicates the new users on how to build
Apache HAWQ on macOS quickly.
This commit disables the previous problematic Travis CI as well.

HAWQ-1779. Add GitHub Action for building on macOS

---

.github/workflows/build.yml
.github/workflows/scripts/init_hawq.sh
.github/workflows/scripts/init_hdfs.sh
.github/workflows/scripts/init_macos.sh
depends/libhdfs3/CMakeLists.txt
depends/libyarn/CMakeLists.txt
src/Makefile.global.in

It fixes the install_name of libhdfs and libyarn with @rpath prefix,
which is required when loading executable in different path, and
enforces searching headers and libraries in those self-contained first.

HAWQ-1780. Add GitHub Action Step to Test against Running Instance

---

.github/workflows/scripts/gtest_filter_negative
src/backend/access/external/url.c
src/backend/parser/gram.y

- revise CREATE EXTERNAL TABLE default to READABLE EXTERNAL TABLE
- fix read from EXTERNAL TABLE of GPFDIST protocol
The documented behaviour of CREATE EXTERNAL TABLE indicates a READABLE
TABLE but used to be violated.
Referring to https://curl.se/libcurl/c/curl_multi_fdset.html,
```
If no file descriptors are set by libcurl, max_fd will contain -1 when
this function returns. Otherwise it will contain the highest descriptor
number libcurl set. When libcurl returns -1 in max_fd, it is because
libcurl currently does something that isn't possible for your
application to monitor with a socket and unfortunately you can then not
know exactly when the current action is completed using select(). You
then need to wait a while before you proceed and call curl_multi_perform
anyway. How long to wait? …
```

HAWQ-1782. Fix failed to read EXTERNAL TABLE of GPFDIST protocol

---

depends/libhdfs3/src/common/SessionConfig.cpp

Instead of setting empty string, an example value from HDFS doc should
be better to follow.
https://hadoop.apache.org/docs/current/hadoop-project-dist/hadoop-hdfs/ShortCircuitLocalReads.html
Signed-off-by: Yuan Zhou <yuan.zhou@intel.com>

HAWQ-1788: set default value for dfs.domain.socket.path
